server:
  port: 8081
  ssl:
    enabled: false
  servlet:
    context-path: /api/v1

spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: blogsdb

logging:
  level:
    enabled: DEBUG
    org.springframework.data.mongodb: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicTypeDescriptor: TRACE